blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/mksinha01/Flexi-Bot/blob/main/README.md
    about: Check our README for installation and usage instructions
  - name: 💬 Discussions
    url: https://github.com/mksinha01/Flexi-Bot/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚨 Security Issues
    url: https://github.com/mksinha01/Flexi-Bot/security/advisories/new
    about: Report security vulnerabilities privately